# fly.toml app configuration file generated for bitter-feather-4281 on 2023-07-23T18:45:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-feather-4281"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
